source 'https://cdn.cocoapods.org/'

use_frameworks!

platform :ios, '13.0'

target 'OnePaySDK_Example' do
  
  pod '1PaySDK', '~>1.0.0-beta2'

  target 'OnePaySDK_Tests' do
    inherit! :search_paths

    
  end
end
